version: '2'
services:

  # create self-signed server certificate for satsrv04
  gencert:
    build: ../../image/gencert
    image: webofneeds/gencert:int
    environment:
      - "constraint:node==satsrv04"
      - "CN=satsrv04.researchstudio.at"
      - "PASS=pass:$won_certificate_passwd"
    volumes:
      - $base_folder/won-server-certs:/usr/local/certs/out/

  # portsgres need databases for owner and wonnode
  postgres:
    image: webofneeds/postgres:int
    build: ../../image/postgres
    environment:
      - "constraint:node==satsrv04"
      - "POSTGRES_PASSWORD=$postgres_db_passwd"
      - "PGDATA=/var/lib/postgresql/data/pgdata"
    ports:
      - "5433:5432"

  # wonnode on satsrv04 (without proxy) => https://satsrv04:8889/won
  wonnode:
    build: ../../image/wonnode
    image: webofneeds/wonnode:int
    environment:
      - "constraint:node==satsrv04"
      - "uri.host=satsrv04.researchstudio.at"
      - "http.port=8889"
      - "db.sql.jdbcDriverClass=org.postgresql.Driver"
      - "db.sql.jdbcUrl=jdbc:postgresql://satsrv04.researchstudio.at:5433/won_node"
      - "db.sql.user=won"
      - "db.sql.password=$postgres_db_passwd"
      - "CERTIFICATE_PASSWORD=$won_certificate_passwd"
      - "activemq.broker.port=61617"
      - "JMEM_OPTS=-XX:+HeapDumpOnOutOfMemoryError"
      - "JMX_OPTS=-javaagent:/opt/agent/inspectit-agent.jar -Dinspectit.repository=satsrv07.researchstudio.at:9070
        -Dinspectit.agent.name=int_satsrv04_wonnode
        -Xdebug -Xrunjdwp:transport=dt_socket,address=62910,server=y,suspend=n
        -Dcom.sun.management.jmxremote.port=9010 -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.rmi.port=9010
        -Djava.rmi.server.hostname=satsrv04.researchstudio.at"
    ports:
      - "8889:8443"
      - "61617:61617"
      - "62910:62910"
      - "9010:9010"
    volumes:
      - $base_folder/won-server-certs:/usr/local/tomcat/conf/ssl/
      - $base_folder/won-client-certs/wonnode:/usr/local/tomcat/won/client-certs/
      - $base_folder/agent:/opt/agent/
    depends_on:
      - postgres
      - gencert

  # owner on satsrv04 (without proxy) => https://satsrv04:8082/owner
  owner:
    build: ../../image/owner
    image: webofneeds/owner:int
    environment:
      - "constraint:node==satsrv04"
      - "node.default.host=satsrv04.researchstudio.at"
      - "uri.host=satsrv04.researchstudio.at"
      - "http.port=8082"
      - "node.default.http.port=8889"
      - "db.sql.jdbcDriverClass=org.postgresql.Driver"
      - "db.sql.jdbcUrl=jdbc:postgresql://satsrv04.researchstudio.at:5433/won_owner"
      - "db.sql.user=won"
      - "db.sql.password=$postgres_db_passwd"
      - "CERTIFICATE_PASSWORD=$won_certificate_passwd"
      - "email.from.won.user=$MAIL_USER"
      - "email.from.won.password=$MAIL_PASS"
      - "email.from.won.smtp.host=$MAIL_HOST"
      - "JMEM_OPTS=-XX:+HeapDumpOnOutOfMemoryError"
      - "JMX_OPTS=-javaagent:/opt/agent/inspectit-agent.jar -Dinspectit.repository=satsrv07.researchstudio.at:9070
        -Dinspectit.agent.name=int_satsrv04_owner
        -Xdebug -Xrunjdwp:transport=dt_socket,address=62911,server=y,suspend=n
        -Dcom.sun.management.jmxremote.port=9011 -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.rmi.port=9011
        -Djava.rmi.server.hostname=satsrv04.researchstudio.at"
    ports:
      - "8082:8443"
      - "62911:62911"
      - "9011:9011"
    volumes:
      - $base_folder/won-server-certs:/usr/local/tomcat/conf/ssl/
      - $base_folder/won-client-certs/owner:/usr/local/tomcat/won/client-certs/
      - $base_folder/agent:/opt/agent/
    depends_on:
      - wonnode
      - postgres
      - gencert

