version: '2'
services:

  # create self-signed server certificate for satsrv05 and satsrv06 (nginx proxy)
  gencert:
    build: ../../image/gencert
    image: webofneeds/gencert:int
    environment:
      - "CN=satsrv06.researchstudio.at"
      - "PASS=pass:$won_certificate_passwd"
      - "OPENSSL_CONFIG_FILE=/usr/local/openssl.conf"
    volumes:
      - $base_folder/won-server-certs:/usr/local/certs/out/
      - $base_folder/openssl-int.conf:/usr/local/openssl.conf

  # portsgres need databases for owner and wonnode
  postgres:
    image: webofneeds/postgres:int
    build: ../../image/postgres
    environment:
      - "POSTGRES_PASSWORD=$postgres_db_passwd"
      - "PGDATA=/var/lib/postgresql/data/pgdata"
    volumes:
      - $base_folder/postgres/data/pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"

  # wonnode on satsrv05 (with proxy on satsrv06) => https://satsrv06/won
  wonnode:
    build: ../../image/wonnode
    image: webofneeds/wonnode:int
    environment:
      - "uri.host=satsrv06.researchstudio.at"
      - "http.port=8889"
      - "uri.prefix=https://satsrv06.researchstudio.at/won"
      - "client.authentication.behind.proxy=true"
      - "db.sql.jdbcDriverClass=org.postgresql.Driver"
      - "db.sql.jdbcUrl=jdbc:postgresql://satsrv05.researchstudio.at:5433/won_node"
      - "db.sql.user=won"
      - "db.sql.password=$postgres_db_passwd"
      - "db.ddl.strategy=validate"
      - "CERTIFICATE_PASSWORD=$won_certificate_passwd"
      - "activemq.broker.port=61617"
      - "JMEM_OPTS=-XX:+HeapDumpOnOutOfMemoryError"
      - "JMX_OPTS=-javaagent:/opt/agent/inspectit-agent.jar -Dinspectit.repository=satsrv07.researchstudio.at:9070
        -Dinspectit.agent.name=int_satsrv05_wonnode
        -Xdebug -Xrunjdwp:transport=dt_socket,address=62912,server=y,suspend=n
        -Dcom.sun.management.jmxremote.port=9012 -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.rmi.port=9012
        -Djava.rmi.server.hostname=satsrv05.researchstudio.at"
    ports:
      - "8889:8443"
      - "61617:61617"
      - "62912:62912"
      - "9012:9012"
    volumes:
      - $base_folder/won-server-certs:/usr/local/tomcat/conf/ssl/
      - $base_folder/won-client-certs/wonnode:/usr/local/tomcat/won/client-certs/
      - $base_folder/agent:/opt/agent/
    depends_on:
      - postgres
      - gencert

   # owner on satsrv05 (with proxy on satsrv06) => https://satsrv06/
  owner:
    build: ../../image/owner
    image: webofneeds/owner:int
    environment:
      - "node.default.host=satsrv06.researchstudio.at"
      - "uri.host=satsrv06.researchstudio.at"
      - "http.port=8082"
      - "node.default.http.port=443"
      - "uri.prefix=https://satsrv06.researchstudio.at"
      - "uri.prefix.node.default=https://satsrv06.researchstudio.at/won"
      - "db.sql.jdbcDriverClass=org.postgresql.Driver"
      - "db.sql.jdbcUrl=jdbc:postgresql://satsrv05.researchstudio.at:5433/won_owner"
      - "db.sql.user=won"
      - "db.sql.password=$postgres_db_passwd"
      - "db.ddl.strategy=validate"
      - "CERTIFICATE_PASSWORD=$won_certificate_passwd"
      - "email.from.won.user=$MAIL_USER"
      - "email.from.won.password=$MAIL_PASS"
      - "email.from.won.smtp.host=$MAIL_HOST"
      - "JMEM_OPTS=-XX:+HeapDumpOnOutOfMemoryError"
      - "JMX_OPTS=-javaagent:/opt/agent/inspectit-agent.jar -Dinspectit.repository=satsrv07.researchstudio.at:9070
        -Dinspectit.agent.name=int_satsrv05_owner
        -Xdebug -Xrunjdwp:transport=dt_socket,address=62913,server=y,suspend=n
        -Dcom.sun.management.jmxremote.port=9013 -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.rmi.port=9013
        -Djava.rmi.server.hostname=satsrv05.researchstudio.at"
    ports:
      - "8082:8443"
      - "62913:62913"
      - "9013:9013"
    volumes:
      - $base_folder/won-server-certs:/usr/local/tomcat/conf/ssl/
      - $base_folder/won-client-certs/owner:/usr/local/tomcat/won/client-certs/
      - $base_folder/agent:/opt/agent/
    depends_on:
      - wonnode
      - postgres
      - gencert
