version: '2'
services:

  # nginx proxy server on satsrv07 for owner and wonnode on host satsrv05
  nginx:
    image: nginx
    environment:
      - "constraint:node==satsrv07"
    ports:
      - "80:80"
      - "443:443"
      - "61616:61616"
    volumes:
      - $base_folder/nginx-master.conf:/etc/nginx/nginx.conf
      - $base_folder/won-server-certs:/etc/nginx/won-server-certs/
